# Generated by Django 5.2.6 on 2025-10-01 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_meto', models.CharField(max_length=50, unique=True)),
                ('imagen_metodo', models.ImageField(blank=True, null=True, upload_to='metodos_pago_imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pagos.metodopago')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.orden')),
            ],
        ),
    ]
