# Generated by Django 5.2.6 on 2025-10-01 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carritos', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_entrega', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente_envio', 'Pendiente de Envío'), ('preparando_envio', 'Preparando Envío'), ('en_transito', 'En Tránsito'), ('en_reparto', 'En Reparto'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=30)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carritos.carritos')),
                ('distrito_entrega', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.distrito')),
                ('pais_entrega', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.pais')),
                ('provincia_entrega', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.provincia')),
            ],
        ),
    ]
