# Generated by Django 5.2.6 on 2025-10-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carritos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritos',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
    ]
