# Generated by Django 5.2.6 on 2025-10-01 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('codigo_pais', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.codigopais')),
                ('distrito', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.distrito')),
                ('pais', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.pais')),
                ('provincia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.provincia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
    ]
